name: File Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy-files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./files/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
